spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://192.168.56.10:3306/cloudmall_sms
    driverClassName: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: cloudmall-coupon
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.10
    pool: 6379

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 7000

logging:
  level:
    com.hungwen.cloudmall.coupon: debug
#logging:
#  level:
#    com.hungwen.cloudmall: info
#    org.springframework.cloud.openfeign: debug
#    org.springframework.cloud.sleuth: debug

#暴露所有端點
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'