server:
  port: 40000

spring:
  application:
    name: cloudmall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    port: 6379
    host: 192.168.56.10
  session:
    store-type: redis

# 設定線程池
cloudmall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10