server:
  port: 40000

spring:
  application:
    name: cloudmall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #    sentinel:
  #      transport:
  #        #配置 sentinel dashboard地址
  #        dashboard: localhost:8080
  redis:
    port: 6379
    host: 192.168.56.10
  #開啟 feign 對 sentinel 的支持
  #feign:
  #  sentinel:
  #    enabled: true
  session:
    store-type: redis
#配置線程池
cloudmall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10
#暴露所有端點
management:
  endpoints:
    web:
      exposure:
        include: '*'


