server:
  port: 12000

spring:
  application:
    name: cloudmall-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  sentinel:
    transport:
      dashboard: localhost:8083
  redis:
    host: 192.168.56.10
    port: 6379
  session:
    store-type: redis

logging:
  level:
    com.hungwen.cloudmall.search: debug
  pattern:
    console: "%d{yyyy-MM-dd} [%thread] - %msg%n"

