server:
  port: 25000

spring:
  application:
    name: cloudmall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.56.10
    port: 6379
  thymeleaf:
    cache: false
  # 配置異步任務線程池
  task:
    execution:
      pool:
        core-size: 5
        max-size: 50
  session:
    store-type: redis