spring:
  cloud:
    gateway:
      routes:
        #        - id: query_route_1
        #          uri: https://www.baidu.com
        #          predicates:
        #            - Query=baidu, lgh
        #
        #        - id: query_route_2
        #          uri: https://www.qq.com
        #          predicates:
        #            - Query=qq, lgh

        - id: product_route
          uri: lb://cloudmall-product
          predicates:
            - Path=/api/product/**,/hello
          filters:
            - RewritePath=/api(?<segment>.*),/$\{segment}

        - id: coupon_route
          uri: lb://cloudmall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api(?<segment>.*),/$\{segment}

        - id: thirdparty_route
          uri: lb://cloudmall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://cloudmall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://cloudmall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>.*),/renren-fast/$\{segment}

        - id: cloudmall_host_route
          uri: lb://cloudmall-product
          predicates:
            - Host=cloudmall.com,item.cloudmall.com

        - id: cloudmall_search_route
          uri: lb://cloudmall-search
          predicates:
            - Host=search.cloudmall.com

        - id: cloudmall_auth_route
          uri: lb://cloudmall-auth-server
          predicates:
            - Host=auth.cloudmall.com

        - id: cloudmall_cart_route
          uri: lb://cloudmall-cart
          predicates:
            - Host=cart.cloudmall.com

        - id: cloudmall_order_route
          uri: lb://cloudmall-order
          predicates:
            - Host=order.cloudmall.com

        - id: cloudmall_member_route
          uri: lb://cloudmall-member
          predicates:
            - Host=member.cloudmall.com

        - id: cloudmall_seckill_route
          uri: lb://cloudmall-seckill
          predicates:
            - Host=seckill.cloudmall.com