spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://192.168.56.10:3306/cloudmall_pms
    driverClassName: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: cloudmall-product
#    alicloud:
#      access-key: LTAI4FxwBwJsK4Fp4cBX8CgB
#      secret-key: KZgasxP1VGyli7vOf6AlsZlU1mSHbX
#      oss:
#        endpoint: oss-cn-hongkong.aliyuncs.com
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#  thymeleaf:
#    cache: false
#  redis:
#    host: 192.168.56.10
#    pool: 6379

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 10000

logging:
  level:
    com.hungwen.cloudmall.product: debug
#    org.springframework.cloud.openfeign: debug
#    org.springframework.cloud.sleuth: debug