spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql-master.cloudmall:3306/cloudmall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  redis:
    host: 192.168.80.133
    port: 6379


mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/**/*.xml
server:
  port: 8080
logging:
  level:
    com.xhh.cloudmall.product: info