kind: Deployment
apiVersion: apps/v1
metadata:
  name: cloudmall-memer
  namespace: kubesphere-sample-prod
  labels:
    app: cloudmall-memer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudmall-memer
  template:
    metadata:
      labels:
        app: cloudmall-memer
    spec:
      containers:
        - name: cloudmall-memer
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$TAG_NAME
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: cloudmall-memer
  namespace: kubesphere-sample-prod
  labels:
    app: cloudmall-memer
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 20006
  selector:
    app: cloudmall-memer
  type: NodePort
  sessionAffinity: None