spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://mysql.kubesphere-sample-prod:3306/cloudmall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: cloudmall-ware
  jackson:
    date-format: yyyy-MM-dd
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml
server:
  port: 8080