spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://mysql-master.cloudmall:3306/cloudmall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: cloudmall-member
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml
server:
  port: 8080